#ifndef _POWER_INTERFACE_H
#define _POWER_INTERFACE_H

#define POWER_INTERFACE_MAGIC_NO 'B'

#define POWER_INTERFACE_REBOOT  	_IO(POWER_INTERFACE_MAGIC_NO, 0x5)
#define POWER_INTERFACE_SHUTDOWN	_IO(POWER_INTERFACE_MAGIC_NO, 0x6)

#define POWER_INTERFACE_STARTUP_READ  	_IO(POWER_INTERFACE_MAGIC_NO, 0x7)
#define POWER_INTERFACE_STARTUP_WRITE	_IO(POWER_INTERFACE_MAGIC_NO, 0x8)
#define POWER_INTERFACE_STARTUP_READ_R1	_IO(POWER_INTERFACE_MAGIC_NO, 0x9)

#endif
