#ifndef __LINUX_HS_MODEM_HW_H_
#define __LINUX_HS_MODEM_HW_H_
/* ----------------------------
 *           includes
 * ----------------------------
 */

/* ----------------------------
 *           macros
 * ----------------------------
 */

/* ----------------------------
 *      Registers offeset
 * ----------------------------
 */
#define HSMDM_REG_VERSION_OFFSET				0x00
#define HSMDM_REG_REVISION_OFFSET				0xfe

#define HSMDM_REG_FREQ_EST_OFFSET				0x06
#define HSMDM_REG_EBN0_OFFSET					0x07
#define HSMDM_REG_IRQ_SEL_OFFSET				0x19
#define HSMDM_REG_TX_IRQ_RST_OFFSET				0x1A
#define HSMDM_REG_RST_OFFSET					0x1B

#define HSMDM_REG_TDD_MODE_OFFSET				0x3F // stop when finish
#define HSMDM_REG_ENG_THRSH_OFFSET				0x54
#define HSMDM_REG_REL_THRSH_OFFSET				0x55
#define HSMDM_REG_IER_OFFSET					0x66
#define HSMDM_REG_RX_CRC_OK_OFFSET				0x67

#define HSMDM_REG_TX_TIMESTAMP_OFFSET			0x70
#define HSMDM_REG_RX_TIMESTAMP_OFFSET			0x71

#define HSMDM_REG_TXINT_EARLYOFFSET_OFFSET		0x72
#define HSMDM_REG_RXINT_TIMEOUTMAX_OFFSET		0x73
#define HSMDM_REG_RXINT_TIMEOUTPERIOD_OFFSET	0x74
#define HSMDM_REG_RXINT_TIMETOLERANCE_OFFSET	0x75

#define HSMDM_REG_RX_FIFO_A_DATA_OFFSET			0x76
#define HSMDM_REG_RX_FIFO_A_COUNT_OFFSET		0x77
#define HSMDM_REG_RX_FIFO_B_DATA_OFFSET			0x78
#define HSMDM_REG_RX_FIFO_B_COUNT_OFFSET		0x79
#define HSMDM_REG_RX_FIFO_A_B_VALID_OFFSET		0x7A

#define HSMDM_REG_TX_FIFO_A_B_VALID_OFFSET		0x7B
#define HSMDM_REG_TX_FIFO_A_DATA_OFFSET			0x7C
#define HSMDM_REG_TX_FIFO_B_DATA_OFFSET			0x7D
#define HSMDM_REG_TX_PCK_END_OFFSET				0x7E
// [1]- rxTolKeepIrqEn, [0]- rxTimeoutEnable
#define HSMDM_REG_RX_IRQ_CTRL_OFFSET			0x7F


#define HSMDM_REG_RX_PACKET_SIZE_OFFSET		0x2E
#define HSMDM_REG_RX_sSPREAD_OFFSET			0x22
#define HSMDM_REG_RX_CORE_DELAY_OFFSET		0x23
#define HSMDM_REG_RX_sDYN_SCITO_OFFSET		0x24
#define HSMDM_REG_RX_sWIN_DELAY_OFFSET		0x25
#define HSMDM_REG_RX_sDET_WIN_OFFSET		0x26
#define HSMDM_REG_RX_dDET_OFFSET_OFFSET		0x27
#define HSMDM_REG_RX_dDSS_FACTOR_OFFSET		0x28
#define HSMDM_REG_RX_dDATA_LEN_OFFSET		0x29
#define HSMDM_REG_RX_dTCC_BLOCK_OFFSET		0x2B
#define HSMDM_REG_RX_dCOD_BLOCK_OFFSET		0x2C
#define HSMDM_REG_RX_CIC_RATIO_OFFSET		0x38
#define HSMDM_REG_RX_CIC_SCALE_OFFSET		0x39
#define HSMDM_REG_RX_RESAMP_FRAC_L_OFFSET	0x3A
#define HSMDM_REG_RX_RESAMP_FRAC_H_OFFSET	0x3B
#define HSMDM_REG_RX_NUM_TAPS_OFFSET		0x4E
#define HSMDM_REG_CHANGE_RATE_FLAG_OFFSET	0x31

#define HSMDM_REG_TX_PACKET_SIZE_OFFSET		0x1C
#define HSMDM_REG_TX_FRAME_LEN_OFFSET		0x1D
#define HSMDM_REG_TX_ENC_BLK_SIZE_OFFSET	0x1E
#define HSMDM_REG_TX_DSS_FACTOR_OFFSET		0x1F
#define HSMDM_REG_TX_SHAP_INT_CLK_OFFSET	0x32
#define HSMDM_REG_TX_RESAMP_FRAC_L_OFFSET	0x33
#define HSMDM_REG_TX_RESAMP_FRAC_H_OFFSET	0x34
#define HSMDM_REG_TX_RESAMP_INT_OFFSET		0x35
#define HSMDM_REG_TX_CIC_INT_RATE_OFFSET	0x36
#define HSMDM_REG_TX_CIC_SCALE_OFFSET		0x37

/* ----------------------------
 *        REG IER Masks
 * ----------------------------
 */
#define HSMODEM_RX_ONLY_MASK	0X00000001
#define HSMODEM_TX_ONLY_MASK	0X00000002
#define HSMODEM_RX_TX_MASK		(HSMODEM_RX_ONLY_MASK | HSMODEM_TX_ONLY_MASK)

/* ----------------------------
 *        REG RX_IRQ_CTRL Masks
 * ----------------------------
 */
#define HSMDM_RX_IRQ_EN_DUMMY_MASK	1
#define HSMDM_RX_IRQ_EN_TOL_MASK	2

#endif /* __LINUX_HS_MODEM_HW_H_ */
